import { env } from './config/env.js';
import { createDb } from './db/database.js';
import { EconomyService } from './services/economy.service.js';
import { QuizHistoryStore } from './services/quiz-history.service.js';
import { PrefixStore } from './services/prefix.service.js';
import { LotteryService } from './services/lottery.service.js';
import { ActivityService } from './services/activity.service.js';
import { ReportService } from './services/report.service.js';
import { CashService } from './services/cash.service.js';
import { ItemsService } from './services/items.service.js';
import { BuffService } from './services/buff.service.js';
import { TopupService } from './services/topup.service.js';
import { DashboardService } from './services/dashboard.service.js';
import { ProfileService } from './services/profile.service.js';
import { LuckService } from './services/luck.service.js';
import { FigurineService } from './services/figurine.service.js';

export const db = createDb(env.DB_PATH);
export const buffs = new BuffService(db);
export const economy = new EconomyService(db, buffs);
export const quizHistory = new QuizHistoryStore(db);
export const prefixes = new PrefixStore(db);
export const lottery = new LotteryService(db, economy);
export const activity = new ActivityService(db);
export const reports = new ReportService(db);
export const cash = new CashService(db);
export const items = new ItemsService(db);
export const topups = new TopupService(db, cash);
export const dashboard = new DashboardService(db);
export const profiles = new ProfileService(db);
export const luck = new LuckService(db);
export const figurines = new FigurineService(db);
